alias p=print
alias c=copy
alias d=delete
alias del=delete
alias e=edit
alias f=find
alias g=goto
alias go=goto
alias h=help
alias l=list
alias m=move
alias q=quit
alias exit=quit
alias r=read
alias w=write
alias sh=shell
alias dsk=disk
alias mem=memory
alias kbd=keyboard
# alias cd=goto
# alias rm=delete
# alias ls=list
# alias cp=copy
# alias mv=move
