timeout: 10
graphics: no

/MOROS (Limine)
    protocol: limine
    resolution: 640x480x32
    kernel_path: boot():/kernel.elf

/MOROS (Multiboot2)
    protocol: multiboot2
    textmode: yes
    kernel_path: boot():/kernel.elf
