(def (floor x)
  (if (>= x 0.0)
    (trunc x)
    (if (= x (trunc x))
      (trunc x)
      (- (trunc x) 1))))

(def (ceil x)
  (if (<= x 0.0)
    (trunc x)
    (if (= x (trunc x))
      (trunc x)
      (+ (trunc x) 1))))

(def (round x)
  (let (a b) ((floor x) (ceil x))
    (if (< (- x a) 0.5) a b)))
