timeout: 0
graphics: no
serial: no
default_entry: multiboot
/limine
    protocol: limine
    resolution: 640x480x32
    kernel_path: boot():/kernel.elf
/multiboot
    protocol: multiboot2
    textmode: yes
    kernel_path: boot():/kernel.elf
